/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface BenefitDto
 */
export interface BenefitDto {
    /**
     * 
     * @type {string}
     * @memberof BenefitDto
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof BenefitDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof BenefitDto
     */
    'title'?: string;
}
/**
 * 
 * @export
 * @interface CostDto
 */
export interface CostDto {
    /**
     * 
     * @type {number}
     * @memberof CostDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CostDto
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof CostDto
     */
    'value'?: number;
}
/**
 * 
 * @export
 * @interface IdeaDto
 */
export interface IdeaDto {
    /**
     * 
     * @type {boolean}
     * @memberof IdeaDto
     */
    'anonymous'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof IdeaDto
     */
    'authorId'?: number;
    /**
     * 
     * @type {Array<BenefitDto>}
     * @memberof IdeaDto
     */
    'benefits'?: Array<BenefitDto>;
    /**
     * 
     * @type {boolean}
     * @memberof IdeaDto
     */
    'blocked'?: boolean;
    /**
     * 
     * @type {Array<CostDto>}
     * @memberof IdeaDto
     */
    'costs'?: Array<CostDto>;
    /**
     * 
     * @type {string}
     * @memberof IdeaDto
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdeaDto
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof IdeaDto
     */
    'id'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof IdeaDto
     */
    'keywords'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof IdeaDto
     */
    'status'?: IdeaDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof IdeaDto
     */
    'statusDescription'?: string;
    /**
     * 
     * @type {number}
     * @memberof IdeaDto
     */
    'subjectId'?: number;
    /**
     * 
     * @type {string}
     * @memberof IdeaDto
     */
    'title'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum IdeaDtoStatusEnum {
    New = 'New',
    Accepted = 'Accepted',
    Rejected = 'Rejected',
    ReuqestForDetails = 'ReuqestForDetails',
    PutAway = 'PutAway'
}

/**
 * 
 * @export
 * @interface SubjectDto
 */
export interface SubjectDto {
    /**
     * 
     * @type {string}
     * @memberof SubjectDto
     */
    'audience'?: SubjectDtoAudienceEnum;
    /**
     * 
     * @type {number}
     * @memberof SubjectDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SubjectDto
     */
    'name'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SubjectDtoAudienceEnum {
    Student = 'Student',
    Employee = 'Employee',
    Committee = 'Committee',
    Admin = 'Admin'
}


/**
 * InnowacjaAPIApi - axios parameter creator
 * @export
 */
export const InnowacjaAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete Idea with given id (also deletes all of its attachments, costs and benefits)
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteIdeaUsingDELETE: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteIdeaUsingDELETE', 'id', id)
            const localVarPath = `/ideas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary downloadAttachment
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadAttachmentUsingGET: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('downloadAttachmentUsingGET', 'id', id)
            const localVarPath = `/attachments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get simplified DTO\'s of all ideas in database (without costs, benefits or attachments)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllIdeasUsingGET: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ideas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all subjects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUsingGET: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/subjects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get list of attachment id\'s belonging to given idea.
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttachmentIdsUsingGET: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getAttachmentIdsUsingGET', 'id', id)
            const localVarPath = `/ideas/{id}/attachments`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get subject with given id
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByIdUsingGET: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getByIdUsingGET', 'id', id)
            const localVarPath = `/subjects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get idea with given id
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIdeaByIdUsingGET: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getIdeaByIdUsingGET', 'id', id)
            const localVarPath = `/ideas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all ideas with given subject
         * @param {number} subjectId subjectId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIdeasBySubjectUsingGET: async (subjectId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subjectId' is not null or undefined
            assertParamExists('getIdeasBySubjectUsingGET', 'subjectId', subjectId)
            const localVarPath = `/ideas/by-subject`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (subjectId !== undefined) {
                localVarQueryParameter['subjectId'] = subjectId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Save attachment for given ideaId
         * @param {number} id id
         * @param {any} file file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveAttachmentUsingPOST: async (id: number, file: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('saveAttachmentUsingPOST', 'id', id)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('saveAttachmentUsingPOST', 'file', file)
            const localVarPath = `/ideas/{id}/attachments`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Save Idea in database, returns id of saved entity
         * @param {IdeaDto} ideaDto ideaDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveIdeaUsingPOST: async (ideaDto: IdeaDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ideaDto' is not null or undefined
            assertParamExists('saveIdeaUsingPOST', 'ideaDto', ideaDto)
            const localVarPath = `/ideas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ideaDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Save subject in database, returns id of saved entity
         * @param {'Student' | 'Employee' | 'Committee' | 'Admin'} [audience] 
         * @param {number} [id] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveUsingPOST: async (audience?: 'Student' | 'Employee' | 'Committee' | 'Admin', id?: number, name?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/subjects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (audience !== undefined) {
                localVarQueryParameter['audience'] = audience;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Idea in database, returns true if updated or false if saved new entity
         * @param {IdeaDto} ideaDto ideaDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateIdeaUsingPUT: async (ideaDto: IdeaDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ideaDto' is not null or undefined
            assertParamExists('updateIdeaUsingPUT', 'ideaDto', ideaDto)
            const localVarPath = `/ideas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ideaDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InnowacjaAPIApi - functional programming interface
 * @export
 */
export const InnowacjaAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InnowacjaAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete Idea with given id (also deletes all of its attachments, costs and benefits)
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteIdeaUsingDELETE(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteIdeaUsingDELETE(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary downloadAttachment
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadAttachmentUsingGET(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadAttachmentUsingGET(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get simplified DTO\'s of all ideas in database (without costs, benefits or attachments)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllIdeasUsingGET(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IdeaDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllIdeasUsingGET(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get all subjects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllUsingGET(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SubjectDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllUsingGET(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get list of attachment id\'s belonging to given idea.
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAttachmentIdsUsingGET(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<number>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAttachmentIdsUsingGET(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get subject with given id
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByIdUsingGET(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubjectDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByIdUsingGET(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get idea with given id
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIdeaByIdUsingGET(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IdeaDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getIdeaByIdUsingGET(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get all ideas with given subject
         * @param {number} subjectId subjectId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIdeasBySubjectUsingGET(subjectId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IdeaDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getIdeasBySubjectUsingGET(subjectId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Save attachment for given ideaId
         * @param {number} id id
         * @param {any} file file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveAttachmentUsingPOST(id: number, file: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveAttachmentUsingPOST(id, file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Save Idea in database, returns id of saved entity
         * @param {IdeaDto} ideaDto ideaDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveIdeaUsingPOST(ideaDto: IdeaDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveIdeaUsingPOST(ideaDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Save subject in database, returns id of saved entity
         * @param {'Student' | 'Employee' | 'Committee' | 'Admin'} [audience] 
         * @param {number} [id] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveUsingPOST(audience?: 'Student' | 'Employee' | 'Committee' | 'Admin', id?: number, name?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveUsingPOST(audience, id, name, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update Idea in database, returns true if updated or false if saved new entity
         * @param {IdeaDto} ideaDto ideaDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateIdeaUsingPUT(ideaDto: IdeaDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateIdeaUsingPUT(ideaDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * InnowacjaAPIApi - factory interface
 * @export
 */
export const InnowacjaAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InnowacjaAPIApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete Idea with given id (also deletes all of its attachments, costs and benefits)
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteIdeaUsingDELETE(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteIdeaUsingDELETE(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary downloadAttachment
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadAttachmentUsingGET(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.downloadAttachmentUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get simplified DTO\'s of all ideas in database (without costs, benefits or attachments)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllIdeasUsingGET(options?: any): AxiosPromise<Array<IdeaDto>> {
            return localVarFp.getAllIdeasUsingGET(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all subjects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUsingGET(options?: any): AxiosPromise<Array<SubjectDto>> {
            return localVarFp.getAllUsingGET(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get list of attachment id\'s belonging to given idea.
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttachmentIdsUsingGET(id: number, options?: any): AxiosPromise<Array<number>> {
            return localVarFp.getAttachmentIdsUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get subject with given id
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByIdUsingGET(id: number, options?: any): AxiosPromise<SubjectDto> {
            return localVarFp.getByIdUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get idea with given id
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIdeaByIdUsingGET(id: number, options?: any): AxiosPromise<IdeaDto> {
            return localVarFp.getIdeaByIdUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all ideas with given subject
         * @param {number} subjectId subjectId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIdeasBySubjectUsingGET(subjectId: number, options?: any): AxiosPromise<Array<IdeaDto>> {
            return localVarFp.getIdeasBySubjectUsingGET(subjectId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Save attachment for given ideaId
         * @param {number} id id
         * @param {any} file file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveAttachmentUsingPOST(id: number, file: any, options?: any): AxiosPromise<number> {
            return localVarFp.saveAttachmentUsingPOST(id, file, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Save Idea in database, returns id of saved entity
         * @param {IdeaDto} ideaDto ideaDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveIdeaUsingPOST(ideaDto: IdeaDto, options?: any): AxiosPromise<number> {
            return localVarFp.saveIdeaUsingPOST(ideaDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Save subject in database, returns id of saved entity
         * @param {'Student' | 'Employee' | 'Committee' | 'Admin'} [audience] 
         * @param {number} [id] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveUsingPOST(audience?: 'Student' | 'Employee' | 'Committee' | 'Admin', id?: number, name?: string, options?: any): AxiosPromise<number> {
            return localVarFp.saveUsingPOST(audience, id, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Idea in database, returns true if updated or false if saved new entity
         * @param {IdeaDto} ideaDto ideaDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateIdeaUsingPUT(ideaDto: IdeaDto, options?: any): AxiosPromise<boolean> {
            return localVarFp.updateIdeaUsingPUT(ideaDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteIdeaUsingDELETE operation in InnowacjaAPIApi.
 * @export
 * @interface InnowacjaAPIApiDeleteIdeaUsingDELETERequest
 */
export interface InnowacjaAPIApiDeleteIdeaUsingDELETERequest {
    /**
     * id
     * @type {number}
     * @memberof InnowacjaAPIApiDeleteIdeaUsingDELETE
     */
    readonly id: number
}

/**
 * Request parameters for downloadAttachmentUsingGET operation in InnowacjaAPIApi.
 * @export
 * @interface InnowacjaAPIApiDownloadAttachmentUsingGETRequest
 */
export interface InnowacjaAPIApiDownloadAttachmentUsingGETRequest {
    /**
     * id
     * @type {number}
     * @memberof InnowacjaAPIApiDownloadAttachmentUsingGET
     */
    readonly id: number
}

/**
 * Request parameters for getAttachmentIdsUsingGET operation in InnowacjaAPIApi.
 * @export
 * @interface InnowacjaAPIApiGetAttachmentIdsUsingGETRequest
 */
export interface InnowacjaAPIApiGetAttachmentIdsUsingGETRequest {
    /**
     * id
     * @type {number}
     * @memberof InnowacjaAPIApiGetAttachmentIdsUsingGET
     */
    readonly id: number
}

/**
 * Request parameters for getByIdUsingGET operation in InnowacjaAPIApi.
 * @export
 * @interface InnowacjaAPIApiGetByIdUsingGETRequest
 */
export interface InnowacjaAPIApiGetByIdUsingGETRequest {
    /**
     * id
     * @type {number}
     * @memberof InnowacjaAPIApiGetByIdUsingGET
     */
    readonly id: number
}

/**
 * Request parameters for getIdeaByIdUsingGET operation in InnowacjaAPIApi.
 * @export
 * @interface InnowacjaAPIApiGetIdeaByIdUsingGETRequest
 */
export interface InnowacjaAPIApiGetIdeaByIdUsingGETRequest {
    /**
     * id
     * @type {number}
     * @memberof InnowacjaAPIApiGetIdeaByIdUsingGET
     */
    readonly id: number
}

/**
 * Request parameters for getIdeasBySubjectUsingGET operation in InnowacjaAPIApi.
 * @export
 * @interface InnowacjaAPIApiGetIdeasBySubjectUsingGETRequest
 */
export interface InnowacjaAPIApiGetIdeasBySubjectUsingGETRequest {
    /**
     * subjectId
     * @type {number}
     * @memberof InnowacjaAPIApiGetIdeasBySubjectUsingGET
     */
    readonly subjectId: number
}

/**
 * Request parameters for saveAttachmentUsingPOST operation in InnowacjaAPIApi.
 * @export
 * @interface InnowacjaAPIApiSaveAttachmentUsingPOSTRequest
 */
export interface InnowacjaAPIApiSaveAttachmentUsingPOSTRequest {
    /**
     * id
     * @type {number}
     * @memberof InnowacjaAPIApiSaveAttachmentUsingPOST
     */
    readonly id: number

    /**
     * file
     * @type {any}
     * @memberof InnowacjaAPIApiSaveAttachmentUsingPOST
     */
    readonly file: any
}

/**
 * Request parameters for saveIdeaUsingPOST operation in InnowacjaAPIApi.
 * @export
 * @interface InnowacjaAPIApiSaveIdeaUsingPOSTRequest
 */
export interface InnowacjaAPIApiSaveIdeaUsingPOSTRequest {
    /**
     * ideaDto
     * @type {IdeaDto}
     * @memberof InnowacjaAPIApiSaveIdeaUsingPOST
     */
    readonly ideaDto: IdeaDto
}

/**
 * Request parameters for saveUsingPOST operation in InnowacjaAPIApi.
 * @export
 * @interface InnowacjaAPIApiSaveUsingPOSTRequest
 */
export interface InnowacjaAPIApiSaveUsingPOSTRequest {
    /**
     * 
     * @type {'Student' | 'Employee' | 'Committee' | 'Admin'}
     * @memberof InnowacjaAPIApiSaveUsingPOST
     */
    readonly audience?: 'Student' | 'Employee' | 'Committee' | 'Admin'

    /**
     * 
     * @type {number}
     * @memberof InnowacjaAPIApiSaveUsingPOST
     */
    readonly id?: number

    /**
     * 
     * @type {string}
     * @memberof InnowacjaAPIApiSaveUsingPOST
     */
    readonly name?: string
}

/**
 * Request parameters for updateIdeaUsingPUT operation in InnowacjaAPIApi.
 * @export
 * @interface InnowacjaAPIApiUpdateIdeaUsingPUTRequest
 */
export interface InnowacjaAPIApiUpdateIdeaUsingPUTRequest {
    /**
     * ideaDto
     * @type {IdeaDto}
     * @memberof InnowacjaAPIApiUpdateIdeaUsingPUT
     */
    readonly ideaDto: IdeaDto
}

/**
 * InnowacjaAPIApi - object-oriented interface
 * @export
 * @class InnowacjaAPIApi
 * @extends {BaseAPI}
 */
export class InnowacjaAPIApi extends BaseAPI {
    /**
     * 
     * @summary Delete Idea with given id (also deletes all of its attachments, costs and benefits)
     * @param {InnowacjaAPIApiDeleteIdeaUsingDELETERequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public deleteIdeaUsingDELETE(requestParameters: InnowacjaAPIApiDeleteIdeaUsingDELETERequest, options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).deleteIdeaUsingDELETE(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary downloadAttachment
     * @param {InnowacjaAPIApiDownloadAttachmentUsingGETRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public downloadAttachmentUsingGET(requestParameters: InnowacjaAPIApiDownloadAttachmentUsingGETRequest, options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).downloadAttachmentUsingGET(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get simplified DTO\'s of all ideas in database (without costs, benefits or attachments)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public getAllIdeasUsingGET(options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).getAllIdeasUsingGET(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all subjects
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public getAllUsingGET(options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).getAllUsingGET(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get list of attachment id\'s belonging to given idea.
     * @param {InnowacjaAPIApiGetAttachmentIdsUsingGETRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public getAttachmentIdsUsingGET(requestParameters: InnowacjaAPIApiGetAttachmentIdsUsingGETRequest, options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).getAttachmentIdsUsingGET(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get subject with given id
     * @param {InnowacjaAPIApiGetByIdUsingGETRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public getByIdUsingGET(requestParameters: InnowacjaAPIApiGetByIdUsingGETRequest, options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).getByIdUsingGET(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get idea with given id
     * @param {InnowacjaAPIApiGetIdeaByIdUsingGETRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public getIdeaByIdUsingGET(requestParameters: InnowacjaAPIApiGetIdeaByIdUsingGETRequest, options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).getIdeaByIdUsingGET(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all ideas with given subject
     * @param {InnowacjaAPIApiGetIdeasBySubjectUsingGETRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public getIdeasBySubjectUsingGET(requestParameters: InnowacjaAPIApiGetIdeasBySubjectUsingGETRequest, options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).getIdeasBySubjectUsingGET(requestParameters.subjectId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Save attachment for given ideaId
     * @param {InnowacjaAPIApiSaveAttachmentUsingPOSTRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public saveAttachmentUsingPOST(requestParameters: InnowacjaAPIApiSaveAttachmentUsingPOSTRequest, options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).saveAttachmentUsingPOST(requestParameters.id, requestParameters.file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Save Idea in database, returns id of saved entity
     * @param {InnowacjaAPIApiSaveIdeaUsingPOSTRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public saveIdeaUsingPOST(requestParameters: InnowacjaAPIApiSaveIdeaUsingPOSTRequest, options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).saveIdeaUsingPOST(requestParameters.ideaDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Save subject in database, returns id of saved entity
     * @param {InnowacjaAPIApiSaveUsingPOSTRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public saveUsingPOST(requestParameters: InnowacjaAPIApiSaveUsingPOSTRequest = {}, options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).saveUsingPOST(requestParameters.audience, requestParameters.id, requestParameters.name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Idea in database, returns true if updated or false if saved new entity
     * @param {InnowacjaAPIApiUpdateIdeaUsingPUTRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InnowacjaAPIApi
     */
    public updateIdeaUsingPUT(requestParameters: InnowacjaAPIApiUpdateIdeaUsingPUTRequest, options?: AxiosRequestConfig) {
        return InnowacjaAPIApiFp(this.configuration).updateIdeaUsingPUT(requestParameters.ideaDto, options).then((request) => request(this.axios, this.basePath));
    }
}


