/* tslint:disable */
/* eslint-disable */
/**
 * apsi.backend.social
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AuthenticateDto
 */
export interface AuthenticateDto {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateDto
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateDto
     */
    'password'?: string | null;
}
/**
 * 
 * @export
 * @interface CreatePostDto
 */
export interface CreatePostDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'text'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'socialGroupName'?: string | null;
}
/**
 * 
 * @export
 * @interface LoggedUserDto
 */
export interface LoggedUserDto {
    /**
     * 
     * @type {number}
     * @memberof LoggedUserDto
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {UserRole}
     * @memberof LoggedUserDto
     */
    'userRole'?: UserRole;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    'token'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    'tokenExpirationDate'?: string;
}
/**
 * 
 * @export
 * @interface PostDto
 */
export interface PostDto {
    /**
     * 
     * @type {number}
     * @memberof PostDto
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    'text'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    'date'?: string;
    /**
     * 
     * @type {SocialGroupIdDto}
     * @memberof PostDto
     */
    'socialGroup'?: SocialGroupIdDto;
    /**
     * 
     * @type {UserDto}
     * @memberof PostDto
     */
    'author'?: UserDto;
}
/**
 * 
 * @export
 * @interface SocialGroupDto
 */
export interface SocialGroupDto {
    /**
     * 
     * @type {string}
     * @memberof SocialGroupDto
     */
    'name'?: string | null;
}
/**
 * 
 * @export
 * @interface SocialGroupIdDto
 */
export interface SocialGroupIdDto {
    /**
     * 
     * @type {number}
     * @memberof SocialGroupIdDto
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SocialGroupIdDto
     */
    'name'?: string | null;
}
/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {number}
     * @memberof UserDto
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {UserRole}
     * @memberof UserDto
     */
    'userRole'?: UserRole;
}
/**
 * 
 * @export
 * @enum {string}
 */

export enum UserRole {
    Student = 'Student',
    Employee = 'Employee',
    Committee = 'Committee',
    Admin = 'Admin'
}


/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AuthenticateDto} [authenticateDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authAuthenticatePost: async (authenticateDto?: AuthenticateDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Auth/Authenticate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authenticateDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGetLoggedUserGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Auth/GetLoggedUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {AuthenticateDto} [authenticateDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authAuthenticatePost(authenticateDto?: AuthenticateDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoggedUserDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authAuthenticatePost(authenticateDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authGetLoggedUserGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authGetLoggedUserGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @param {AuthenticateDto} [authenticateDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authAuthenticatePost(authenticateDto?: AuthenticateDto, options?: any): AxiosPromise<LoggedUserDto> {
            return localVarFp.authAuthenticatePost(authenticateDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGetLoggedUserGet(options?: any): AxiosPromise<UserDto> {
            return localVarFp.authGetLoggedUserGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for authAuthenticatePost operation in AuthApi.
 * @export
 * @interface AuthApiAuthAuthenticatePostRequest
 */
export interface AuthApiAuthAuthenticatePostRequest {
    /**
     * 
     * @type {AuthenticateDto}
     * @memberof AuthApiAuthAuthenticatePost
     */
    readonly authenticateDto?: AuthenticateDto
}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @param {AuthApiAuthAuthenticatePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authAuthenticatePost(requestParameters: AuthApiAuthAuthenticatePostRequest = {}, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authAuthenticatePost(requestParameters.authenticateDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authGetLoggedUserGet(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authGetLoggedUserGet(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * PostApi - axios parameter creator
 * @export
 */
export const PostApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreatePostDto} [createPostDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postCreatePostPost: async (createPostDto?: CreatePostDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Post/CreatePost`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPostDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postGetAllGet: async (page?: number, count?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Post/GetAll`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [authorUsername] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postGetPostsByAuthorGet: async (authorUsername?: string, page?: number, count?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Post/GetPostsByAuthor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (authorUsername !== undefined) {
                localVarQueryParameter['AuthorUsername'] = authorUsername;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [id] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postGetPostsByIdGet: async (id?: number, page?: number, count?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Post/GetPostsById`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (id !== undefined) {
                localVarQueryParameter['Id'] = id;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PostApi - functional programming interface
 * @export
 */
export const PostApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PostApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreatePostDto} [createPostDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postCreatePostPost(createPostDto?: CreatePostDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postCreatePostPost(createPostDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postGetAllGet(page?: number, count?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PostDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postGetAllGet(page, count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} [authorUsername] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postGetPostsByAuthorGet(authorUsername?: string, page?: number, count?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PostDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postGetPostsByAuthorGet(authorUsername, page, count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} [id] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postGetPostsByIdGet(id?: number, page?: number, count?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postGetPostsByIdGet(id, page, count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PostApi - factory interface
 * @export
 */
export const PostApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PostApiFp(configuration)
    return {
        /**
         * 
         * @param {CreatePostDto} [createPostDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postCreatePostPost(createPostDto?: CreatePostDto, options?: any): AxiosPromise<number> {
            return localVarFp.postCreatePostPost(createPostDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postGetAllGet(page?: number, count?: number, options?: any): AxiosPromise<Array<PostDto>> {
            return localVarFp.postGetAllGet(page, count, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [authorUsername] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postGetPostsByAuthorGet(authorUsername?: string, page?: number, count?: number, options?: any): AxiosPromise<Array<PostDto>> {
            return localVarFp.postGetPostsByAuthorGet(authorUsername, page, count, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [id] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postGetPostsByIdGet(id?: number, page?: number, count?: number, options?: any): AxiosPromise<PostDto> {
            return localVarFp.postGetPostsByIdGet(id, page, count, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for postCreatePostPost operation in PostApi.
 * @export
 * @interface PostApiPostCreatePostPostRequest
 */
export interface PostApiPostCreatePostPostRequest {
    /**
     * 
     * @type {CreatePostDto}
     * @memberof PostApiPostCreatePostPost
     */
    readonly createPostDto?: CreatePostDto
}

/**
 * Request parameters for postGetAllGet operation in PostApi.
 * @export
 * @interface PostApiPostGetAllGetRequest
 */
export interface PostApiPostGetAllGetRequest {
    /**
     * 
     * @type {number}
     * @memberof PostApiPostGetAllGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof PostApiPostGetAllGet
     */
    readonly count?: number
}

/**
 * Request parameters for postGetPostsByAuthorGet operation in PostApi.
 * @export
 * @interface PostApiPostGetPostsByAuthorGetRequest
 */
export interface PostApiPostGetPostsByAuthorGetRequest {
    /**
     * 
     * @type {string}
     * @memberof PostApiPostGetPostsByAuthorGet
     */
    readonly authorUsername?: string

    /**
     * 
     * @type {number}
     * @memberof PostApiPostGetPostsByAuthorGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof PostApiPostGetPostsByAuthorGet
     */
    readonly count?: number
}

/**
 * Request parameters for postGetPostsByIdGet operation in PostApi.
 * @export
 * @interface PostApiPostGetPostsByIdGetRequest
 */
export interface PostApiPostGetPostsByIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof PostApiPostGetPostsByIdGet
     */
    readonly id?: number

    /**
     * 
     * @type {number}
     * @memberof PostApiPostGetPostsByIdGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof PostApiPostGetPostsByIdGet
     */
    readonly count?: number
}

/**
 * PostApi - object-oriented interface
 * @export
 * @class PostApi
 * @extends {BaseAPI}
 */
export class PostApi extends BaseAPI {
    /**
     * 
     * @param {PostApiPostCreatePostPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostApi
     */
    public postCreatePostPost(requestParameters: PostApiPostCreatePostPostRequest = {}, options?: AxiosRequestConfig) {
        return PostApiFp(this.configuration).postCreatePostPost(requestParameters.createPostDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PostApiPostGetAllGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostApi
     */
    public postGetAllGet(requestParameters: PostApiPostGetAllGetRequest = {}, options?: AxiosRequestConfig) {
        return PostApiFp(this.configuration).postGetAllGet(requestParameters.page, requestParameters.count, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PostApiPostGetPostsByAuthorGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostApi
     */
    public postGetPostsByAuthorGet(requestParameters: PostApiPostGetPostsByAuthorGetRequest = {}, options?: AxiosRequestConfig) {
        return PostApiFp(this.configuration).postGetPostsByAuthorGet(requestParameters.authorUsername, requestParameters.page, requestParameters.count, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PostApiPostGetPostsByIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostApi
     */
    public postGetPostsByIdGet(requestParameters: PostApiPostGetPostsByIdGetRequest = {}, options?: AxiosRequestConfig) {
        return PostApiFp(this.configuration).postGetPostsByIdGet(requestParameters.id, requestParameters.page, requestParameters.count, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * SocialGroupApi - axios parameter creator
 * @export
 */
export const SocialGroupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {SocialGroupDto} [socialGroupDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        socialGroupCreateSocialGroupsPost: async (socialGroupDto?: SocialGroupDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/SocialGroup/CreateSocialGroups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(socialGroupDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        socialGroupSocialGroupsAllGet: async (page?: number, count?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/SocialGroup/SocialGroupsAll`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        socialGroupSocialGroupsGet: async (name?: string, page?: number, count?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/SocialGroup/SocialGroups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (name !== undefined) {
                localVarQueryParameter['Name'] = name;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SocialGroupApi - functional programming interface
 * @export
 */
export const SocialGroupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SocialGroupApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {SocialGroupDto} [socialGroupDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async socialGroupCreateSocialGroupsPost(socialGroupDto?: SocialGroupDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.socialGroupCreateSocialGroupsPost(socialGroupDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async socialGroupSocialGroupsAllGet(page?: number, count?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SocialGroupIdDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.socialGroupSocialGroupsAllGet(page, count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async socialGroupSocialGroupsGet(name?: string, page?: number, count?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SocialGroupIdDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.socialGroupSocialGroupsGet(name, page, count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SocialGroupApi - factory interface
 * @export
 */
export const SocialGroupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SocialGroupApiFp(configuration)
    return {
        /**
         * 
         * @param {SocialGroupDto} [socialGroupDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        socialGroupCreateSocialGroupsPost(socialGroupDto?: SocialGroupDto, options?: any): AxiosPromise<number> {
            return localVarFp.socialGroupCreateSocialGroupsPost(socialGroupDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        socialGroupSocialGroupsAllGet(page?: number, count?: number, options?: any): AxiosPromise<Array<SocialGroupIdDto>> {
            return localVarFp.socialGroupSocialGroupsAllGet(page, count, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        socialGroupSocialGroupsGet(name?: string, page?: number, count?: number, options?: any): AxiosPromise<Array<SocialGroupIdDto>> {
            return localVarFp.socialGroupSocialGroupsGet(name, page, count, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for socialGroupCreateSocialGroupsPost operation in SocialGroupApi.
 * @export
 * @interface SocialGroupApiSocialGroupCreateSocialGroupsPostRequest
 */
export interface SocialGroupApiSocialGroupCreateSocialGroupsPostRequest {
    /**
     * 
     * @type {SocialGroupDto}
     * @memberof SocialGroupApiSocialGroupCreateSocialGroupsPost
     */
    readonly socialGroupDto?: SocialGroupDto
}

/**
 * Request parameters for socialGroupSocialGroupsAllGet operation in SocialGroupApi.
 * @export
 * @interface SocialGroupApiSocialGroupSocialGroupsAllGetRequest
 */
export interface SocialGroupApiSocialGroupSocialGroupsAllGetRequest {
    /**
     * 
     * @type {number}
     * @memberof SocialGroupApiSocialGroupSocialGroupsAllGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof SocialGroupApiSocialGroupSocialGroupsAllGet
     */
    readonly count?: number
}

/**
 * Request parameters for socialGroupSocialGroupsGet operation in SocialGroupApi.
 * @export
 * @interface SocialGroupApiSocialGroupSocialGroupsGetRequest
 */
export interface SocialGroupApiSocialGroupSocialGroupsGetRequest {
    /**
     * 
     * @type {string}
     * @memberof SocialGroupApiSocialGroupSocialGroupsGet
     */
    readonly name?: string

    /**
     * 
     * @type {number}
     * @memberof SocialGroupApiSocialGroupSocialGroupsGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof SocialGroupApiSocialGroupSocialGroupsGet
     */
    readonly count?: number
}

/**
 * SocialGroupApi - object-oriented interface
 * @export
 * @class SocialGroupApi
 * @extends {BaseAPI}
 */
export class SocialGroupApi extends BaseAPI {
    /**
     * 
     * @param {SocialGroupApiSocialGroupCreateSocialGroupsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocialGroupApi
     */
    public socialGroupCreateSocialGroupsPost(requestParameters: SocialGroupApiSocialGroupCreateSocialGroupsPostRequest = {}, options?: AxiosRequestConfig) {
        return SocialGroupApiFp(this.configuration).socialGroupCreateSocialGroupsPost(requestParameters.socialGroupDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SocialGroupApiSocialGroupSocialGroupsAllGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocialGroupApi
     */
    public socialGroupSocialGroupsAllGet(requestParameters: SocialGroupApiSocialGroupSocialGroupsAllGetRequest = {}, options?: AxiosRequestConfig) {
        return SocialGroupApiFp(this.configuration).socialGroupSocialGroupsAllGet(requestParameters.page, requestParameters.count, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SocialGroupApiSocialGroupSocialGroupsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocialGroupApi
     */
    public socialGroupSocialGroupsGet(requestParameters: SocialGroupApiSocialGroupSocialGroupsGetRequest = {}, options?: AxiosRequestConfig) {
        return SocialGroupApiFp(this.configuration).socialGroupSocialGroupsGet(requestParameters.name, requestParameters.page, requestParameters.count, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUsersGet: async (name?: string, page?: number, count?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Users/Users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersUsersGet(name?: string, page?: number, count?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersUsersGet(name, page, count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUsersGet(name?: string, page?: number, count?: number, options?: any): AxiosPromise<Array<UserDto>> {
            return localVarFp.usersUsersGet(name, page, count, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for usersUsersGet operation in UsersApi.
 * @export
 * @interface UsersApiUsersUsersGetRequest
 */
export interface UsersApiUsersUsersGetRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersApiUsersUsersGet
     */
    readonly name?: string

    /**
     * 
     * @type {number}
     * @memberof UsersApiUsersUsersGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof UsersApiUsersUsersGet
     */
    readonly count?: number
}

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @param {UsersApiUsersUsersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersUsersGet(requestParameters: UsersApiUsersUsersGetRequest = {}, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersUsersGet(requestParameters.name, requestParameters.page, requestParameters.count, options).then((request) => request(this.axios, this.basePath));
    }
}


