/* tslint:disable */
/* eslint-disable */
/**
 * apsi.backend.social
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AuthenticateDto
 */
export interface AuthenticateDto {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateDto
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateDto
     */
    'password'?: string | null;
}
/**
 * 
 * @export
 * @interface LoggedUserDto
 */
export interface LoggedUserDto {
    /**
     * 
     * @type {number}
     * @memberof LoggedUserDto
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {UserRole}
     * @memberof LoggedUserDto
     */
    'userRole'?: UserRole;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    'token'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    'tokenExpirationDate'?: string;
}
/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {number}
     * @memberof UserDto
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {UserRole}
     * @memberof UserDto
     */
    'userRole'?: UserRole;
}
/**
 * 
 * @export
 * @enum {string}
 */

export enum UserRole {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}


/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AuthenticateDto} [authenticateDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authAuthenticatePost: async (authenticateDto?: AuthenticateDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Auth/Authenticate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authenticateDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {AuthenticateDto} [authenticateDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authAuthenticatePost(authenticateDto?: AuthenticateDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoggedUserDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authAuthenticatePost(authenticateDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @param {AuthenticateDto} [authenticateDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authAuthenticatePost(authenticateDto?: AuthenticateDto, options?: any): AxiosPromise<LoggedUserDto> {
            return localVarFp.authAuthenticatePost(authenticateDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for authAuthenticatePost operation in AuthApi.
 * @export
 * @interface AuthApiAuthAuthenticatePostRequest
 */
export interface AuthApiAuthAuthenticatePostRequest {
    /**
     * 
     * @type {AuthenticateDto}
     * @memberof AuthApiAuthAuthenticatePost
     */
    readonly authenticateDto?: AuthenticateDto
}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @param {AuthApiAuthAuthenticatePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authAuthenticatePost(requestParameters: AuthApiAuthAuthenticatePostRequest = {}, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authAuthenticatePost(requestParameters.authenticateDto, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUsersGet: async (name?: string, page?: number, count?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Users/Users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersUsersGet(name?: string, page?: number, count?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersUsersGet(name, page, count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUsersGet(name?: string, page?: number, count?: number, options?: any): AxiosPromise<Array<UserDto>> {
            return localVarFp.usersUsersGet(name, page, count, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for usersUsersGet operation in UsersApi.
 * @export
 * @interface UsersApiUsersUsersGetRequest
 */
export interface UsersApiUsersUsersGetRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersApiUsersUsersGet
     */
    readonly name?: string

    /**
     * 
     * @type {number}
     * @memberof UsersApiUsersUsersGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof UsersApiUsersUsersGet
     */
    readonly count?: number
}

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @param {UsersApiUsersUsersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersUsersGet(requestParameters: UsersApiUsersUsersGetRequest = {}, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersUsersGet(requestParameters.name, requestParameters.page, requestParameters.count, options).then((request) => request(this.axios, this.basePath));
    }
}


